### ISSUE TITLE
Rearrange tiles

### ISSUE THREAD

**Issue by AntonyDTA** [TomHarte/SAM-Scroller#39]
Rearrange the tile data to change the row order
from F,D,B,9,7,5,3,1,E,C,A,8,6,4,2,0
to F,D,B,9,7,5,3,1,0,2,4,6,8,A,C,E.
After row 1 instead of LD HL,&0688:ADD HL,SP:LD SP,HL it will be just RES 7,L:LD SP,HL.
(Then instead of 7* DEC H it will be 7* INC H.)
This will save 4 RAM access windows per tile in border (3 in screen).

```
WatTOF:   ;Wait for top of frame with disable interrupt.
          IN A,(&F9)
          BIT 3,A            ;3=Int_Frame, 0=Int_Line
          JR NZ,WaitTOF
          RET
```

**Comment by TomHarte** [comment]
It might also be likely to increase the probability of register content reuse over the fold; my only concern is whether this works for the tiles at the hard-right edge of the screen, where the start address is actually that of the first pixel on the line below as per the Z80's PUSH being predecrement. But I might be worried about nothing.

**Comment by TomHarte** [comment]
Though noting that I already separately compile the rightmost column of tiles for all views except the one that is exactly grid aligned, so I could allocate an extra 8kb for the set where `SET 7` should be used rather than `RES 7`.

Otherwise, yeah, my concern is that the rightmost column starts in the lower right with `HL = &E000` so `L` will be `&00` all the way up the display meaning that in that case I'd need to set bit 7 of L rather than reset it to move down one line.

**Comment by AntonyDTA** [comment]
I missed the fact that the tiles in the rightmost column start with HL pointing to the next row already.
So instead of RES 7,L it would have to be something like this:
```
DEC L
RES 7,L
INC L
```

or
```
LD A,L
XOR &80     ;ADD A,&80
LD L,A
```

It's still faster than the original, although not so much now.
Now this will save 2 RAM access windows per tile in border (1 in screen).

**Comment by TomHarte** [comment]
Frustratingly, I'm not sure either of those works due to lack of carry.

E.g. the tile in the bottom right should start its lowest line from &E000 and therefore its highest from &D880. Which means that the 'move up by one' step needs to move from &D900 to &D880, i.e. with carry from low byte to high.

Whereas the regularly-placed tile to its left should transition from &D8DF to &D878, in which there is no low-to-high carry.

So `DEC *HL*; RES 7, L; INC *HL*` would work but I think has exactly the same performance characteristics as `LD HL, nn; ADD SP, HL`.

It's late at night though, even in this time zone, so possibly I'm struggling in comprehension. Something to sleep on.

**Comment by AntonyDTA** [comment]
I apologize for my faulty suggestions.
This is too much enthusiasm and inattention.
This could be used for a smaller play window where the tiles will not be drawn all the way to the right edge of the screen.

But even though it's a bit more complicated than the idea, there's still a small time saving:
```
DEC HL      ;must be HL 
RES 7,L
INC L       ;just L
LD  SP,HL
```
Now this will save only 1 RAM access windows per tile in border (1 in screen).

**Comment by TomHarte** [comment]
Applied, good thinking! Thanks!
